version: '3.8'

services:
  react:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - fastapi
    networks:
      default:
      net_internal:
        ipv4_address: 192.168.254.10

  fastapi:
    build: ./backend
    environment:
      DB_LOCATION: "/srv/db/app.db"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      default:
      net_internal:
        ipv4_address: 192.168.254.20

networks:
  net_internal:
    internal: true
    ipam:
      config:
        - subnet: 192.168.254.0/24
