project class_divider_db {
  database_type: 'MySQL'
  Note: 'ClassDivider database to store models, students preferences, schedule and results'
}

table jobs {
  id varchar(255) [primary key]
  done boolean
}

table models {
  id integer [primary key, increment]
  job_id varchar(255) [ref: > jobs.id]
  model_data mediumblob
  model_checksum varchar(255)
}

table students {
  id integer [primary key, increment]
  job_id varchar(255) [ref: > jobs.id]
  student_name varchar(255)
}

table students_preferences {
  id integer [primary key, increment]
  student_id integer [ref: > students.id]
  subject varchar(255)
  time_slot_pref varchar(255)
}

table groups {
  id integer [primary key, increment]
  job_id varchar(255) [ref: > jobs.id]
  subject varchar(255)
  time_slot varchar(255)
  capacity integer
}

table results {
  id integer [primary key, increment]
  job_id varchar(255) [ref: > jobs.id]
  student_id integer [ref: > students.id]
  group_id integer [ref: > groups.id]
}
